defaults: 
  # MODEL
  device: 'cuda:0'
  exp_name: 'exp-name'
  levels: 3
  tmp_abs_factor: 4
  model_dir_prefix: null
  enc_dense_layers: 3
  enc_dense_hidden_size: 1000
  cell_type: RSSMCell
  dyn_stoch_size: 32
  dyn_deter_size: 512
  dyn_hidden_size: 512
  enc_emb_size: 200
  dyn_min_stddev: 0.0001
  dyn_mean_only: False
  dyn_reset_state: False
  use_obs: True
  channels_mult: 1
  precision: 32
  act: "SiLU"
  decoder_act: "SiLU"
  dyn_input_layers: 1
  dyn_output_layers: 1
  dyn_rec_depth: 1
  dyn_shared: False
  dyn_discrete: 32
  dyn_mean_act: 'none'
  dyn_std_act: 'softplus'
  dyn_temp_post:  True 
  kl_free: 1.0
  kl_dyn_scale: 0.5
  kl_rep_scale: 0.1
  kl_forward: False 
  unimix_ratio: 0.01
  initial: 'learned' 
  img_size: [64, 64]
  dec_stddev: 1.0
  seed: 42

  # DATASET
  dataset: mmnist
  seq_len: 256
  eval_seq_len: 1000
  channels: 1
  cnn_depth: 32
  encoder_kernels: [4, 4, 4, 4]
  decoder_kernels: [5, 5, 6, 6]
  decoder_thin: True
  datadir: data
  train_num_mmnist_seq: 20000
  val_num_mmnist_seq: 1000
  num_mnist_patch: 10000


  # TRAINING
  batch_size: 128
  eval_batch_size: 24
  num_epochs: 300
  kl_grad_post_perc: null
  free_nats: null

  debug: False 



  # SUMMARIES
  logdir: logs
  open_loop_ctx: 2
  num_val_batches: 1
  save_gifs: True
  save_scalars_every: 1
  save_model_every: 1
  backup_model_every: 50
  eval_every: 20
  train_gif_every: 20



  # World Model
  dyn:
    typ: rssm
    rssm: {deter: 8192, hidden: 1024, stoch: 32, classes: 64, act: silu, norm: rms, unimix: 0.01, outscale: 1.0, winit: normal, imglayers: 2, obslayers: 1, dynlayers: 1, absolute: False, cell: blockgru, blocks: 8, block_fans: False, block_norm: False}
  enc:
    simple: {depth: 64, mults: [1, 2, 3, 4, 4], layers: 3, units: 1024, act: silu, norm: rms, winit: normal, symlog: True, debug_outer: True, kernel: 5, minres: 4}
  dec:
    simple: {inputs: [deter, stoch], vecdist: symlog_mse, depth: 64, mults: [1, 2, 3, 4, 4], layers: 3, units: 1024, act: silu, norm: rms, outscale: 1.0, winit: normal, debug_outer: True, kernel: 5, minres: 4, block_space: 8, block_fans: False, block_norm: False, hidden_stoch: True, space_hidden: 0}
  model_opt: {scaler: adam, lr: 1e-4, eps: 1e-8, globclip: 1000.0, wd: 0.0, warmup: 0}
  winit_scale: 0.0
  loss_scales: {dec_cnn: 1.0, dec_mlp: 1.0, dyn: 1.0, rep: 0.1}
  



jax-003:
  # MODEL
  exp_name: 'jax-003'
  batch_size: 64  
  levels: 1
  dataset: jax_mmnist
  num_epochs: 1000 
